config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :prefecture
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  validates :age, presence: true
  validates :gender, presence: true
  validates :have_house_or_not, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  enum gender: { 男性: 1, 女性: 2, その他: 3 }
  enum payable_amount: { "3万円以下": 3, "4万円以下": 4, "5万円以下": 5, "6万円以下": 6, "7万円以下": 7, "8万円以下": 8, "9万円以下": 9, "12万円以下": 12, "15万円以下": 15, "16万円以上": 16 }
  enum have_house_or_not: { 決まっている: 1, 決まっていない: 2 }
  enum sensitiveness: { キレイ好き: 1, ややキレイ好き: 2, 普通: 3, ややおおざっぱ: 4, おおざっぱ: 5 }

  #indexにてユーザーの絞り込みに使用
  scope :get_by_name, ->(name) {
    where("name like ?", "%#{name}%")
  }
  scope :get_by_gender, ->(gender) {
    where(gender: gender)
  }
  scope :get_by_prefecture_id, ->(prefecture_id) {
    where(prefecture_id: prefecture_id)
  }
  scope :get_by_have_house_or_not, ->(have_house_or_not) {
    where(have_house_or_not: have_house_or_not)
  }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
    if params[:name].present?
      @users = @users.get_by_name params[:name]
    end
    if params[:gender].present?
      @users = @users.get_by_gender params[:gender]
    end
    if params[:prefecture_id].present?
      @users = @users.get_by_prefecture_id params[:prefecture_id]
    end
    if params[:have_house_or_not].present?
      @users = @users.get_by_have_house_or_not params[:have_house_or_not]
    end
  end

  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.prefecture_id
      @prefecture_name = Prefecture.find(@user.prefecture_id).name
    end
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "登録いただいたメールアドレスに、確認メールをお送りしました。メールをご確認下さい。"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_following'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_followers'
  end

  private

    def user_params
      params.require(:user).permit(:name, :gender, :age, :prefecture_id, :have_house_or_not,
                                  :payable_amount, :sensitiveness, :comment, :email, :password,
                                  :password_confirmation)
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def prefecture_choices
    Prefecture.all.map{|prefecture| [prefecture.name, prefecture.id]}
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
    html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 80 %>
  <%= link_to user.name, user %>
  <p><%= user.age %>歳</p>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "削除する", user, method: :delete,
                                  data: { confirm: "本当に削除しますか？" } %>
  <% end %>
  <div class="comment-box">
    <p><%= user.comment %></p>
  </div>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <!-- ユーザーネーム -->
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <!-- 性別 -->
      <div>
        <%= f.label :gender %><br>
        <div class="gender-selector col-xs-3 col-xs-offset-1">
          <label>男性<%= f.radio_button :gender, :男性 %></label>
        </div>
        <div class="gender-selector col-xs-3">
          <label>女性<%= f.radio_button :gender, :女性 %></label>
        </div>
        <div class="gender-selector col-xs-3">
          <label>その他<%= f.radio_button :gender, :その他 %></label>
        </div>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <!-- 年齢 -->
      <div>
        <%= f.label :age %>
        <%= f.select :age, 0..100, include_blank: "選択して下さい" %>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <!-- お住まいになる地域 -->
      <div>
        <%= f.label :prefecture_id %><br>
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, include_blank: "選択して下さい" %>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <!-- お住まいになる家は？ -->
      <div>
        <%= f.label :have_house_or_not %><br>
        <div class="gender-selector col-xs-4 col-xs-offset-1">
          <label>決まっている<%= f.radio_button :have_house_or_not, :決まっている %></label>
        </div>
        <div class="gender-selector col-xs-4">
          <label>決まってない<%= f.radio_button :have_house_or_not, :決まっていない %></label>
        </div>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <!-- 家賃のために負担可能な額 -->
      <div>
        <%= f.label :payable_amount %>
        <%= f.select :payable_amount, [:"3万円以下", :"4万円以下", :"5万円以下", :"6万円以下", :"7万円以下", :"8万円以下", :"9万円以下", :"12万円以下", :"15万円以下", :"16万円以上"], include_blank: "選択して下さい" %>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <div>
        <%= f.label :sensitiveness %><br>
        <div class="col-xs-5 col-xs-offset-1">キレイ好き</div>
        <div class="col-xs-4 laid-back">おおざっぱ</div>
        <div class="gender-selector col-xs-2 col-xs-offset-1">
          <label>１<%= f.radio_button :sensitiveness, :キレイ好き %></label>
        </div>
        <div class="gender-selector col-xs-2">
          <label>２<%= f.radio_button :sensitiveness, :ややキレイ好き %></label>
        </div>
        <div class="gender-selector col-xs-2">
          <label>３<%= f.radio_button :sensitiveness, :普通 %></label>
        </div>
        <div class="gender-selector col-xs-2">
          <label>４<%= f.radio_button :sensitiveness, :ややおおざっぱ %></label>
        </div>
        <div class="gender-selector col-xs-2">
          <label>５<%= f.radio_button :sensitiveness, :おおざっぱ %></label>
        </div>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <div>
        <%= f.label :comment %>
        <%= f.text_area :comment, size: "100x10", :placeholder => "自己紹介や条件等ご記入ください" %>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control', :placeholder => "変更しない場合、記入する必要はありません" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control', :placeholder => "変更しない場合、記入する必要はありません" %>

      <%= f.submit "プロフィールを変更する", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">画像を変更する</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<div>
  <h2>ユーザー検索</h2>
  <%= form_tag(users_path, method: "get") do %>
    <%= label_tag :name, "名前" %><%= text_field_tag :name, params[:name] %>
    <%= label_tag :name, "性別" %>
    <%= select_tag :gender, options_for_select(User.genders, params[:gender]), include_blank: "指定しない" %>
    <%= label_tag :name, "都道府県" %>
    <%= select_tag :prefecture_id, options_from_collection_for_select(Prefecture.all, :id, :name, params[:prefecture_id]), include_blank: "指定しない" %>
    <%= label_tag :name, "住む家の有無" %>
    <%= select_tag :have_house_or_not, options_for_select(User.have_house_or_nots, params[:have_house_or_not]), include_blank: "指定しない" %>
    <%= submit_tag "検索" %>
  <% end %>
</div>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div><br>

      <div>
        <%= f.label :age %>
        <%= f.select :age, 0..100, include_blank: "選択して下さい" %>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <div>
        <%= f.label :gender %><br>
        <div class="gender-selector col-xs-3 col-xs-offset-1">
          <label>男性<%= f.radio_button :gender, :男性 %></label>
        </div>
        <div class="gender-selector col-xs-3">
          <label>女性<%= f.radio_button :gender, :女性 %></label>
        </div>
        <div class="gender-selector col-xs-3">
          <label>その他<%= f.radio_button :gender, :その他 %></label>
        </div>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <div>
        <%= f.label :have_house_or_not %><br>
        <div class="gender-selector col-xs-4 col-xs-offset-1">
          <label>決まっている<%= f.radio_button :have_house_or_not, :決まっている %></label>
        </div>
        <div class="gender-selector col-xs-4">
          <label>決まってない<%= f.radio_button :have_house_or_not, :決まっていない %></label>
        </div>
      </div>

      <!-- 改行用タグ -->
      <span class="clearfix"></span><br>

      <div>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div><br>

      <div>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div><br>

      <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div><br>

      <%= f.submit "アカウントを作成する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <div class="image-name-box">
        <%= gravatar_for @user %>
        <h1><%= @user.name %></h1>
        <% if current_user && current_user.id == params[:id].to_i %>
          <h4><%= @user.email %></h4>
          <div class="follow_edit_area">
            <%= render 'shared/stats' %>
            <%= link_to "プロフィールを編集する", edit_user_path(current_user) %>
          </div>
        <% else %>
          <div class="follow_btn_area">
            <%= render 'follow_form' %>
          </div>
          <% if @isRoom == true %>
            <a href="/rooms/<%= @roomId %>" class="btn user-show-chat">メッセージ</a>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "メッセージ", class:"btn user-show-chat" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="user_show_profile">
        <div>
          <h1>性別</h1>
          <p><%= @user.gender %></p>
        </div>
        <div>
          <h1>年齢</h1>
          <p><%= @user.age %>歳</p>
        </div>
        <div>
          <h1>お住まいになる地域</h1>
          <p><%= @prefecture_name %></p>
        </div>
        <div>
          <h1>お住まいになる家は？</h1>
          <p><%= @user.have_house_or_not %></p>
        </div>
        <div>
          <h1>家賃のために負担可能な額</h1>
          <p><%= @user.payable_amount %></p>
        </div>
        <div>
          <h1>性格</h1>
          <p><%= @user.sensitiveness %></p>
        </div>
        <div>
          <h1>コメント</h1>
          <p><%= @user.comment %></p>
        </div>
      </div>
    </section>
  </aside>
</div>

app/views/users/show_followers.html.erb
<% provide(:title, 'follow') %>
<h1>フォロワー</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @user.followers %>
</ul>

<%= will_paginate %>

app/views/users/show_following.html.erb
<% provide(:title, 'follow') %>
<h1>フォロー中</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @user.following %>
</ul>

<%= will_paginate %>